In [91]:
import numpy as np

In [92]:
lista = list(range(1,11))
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

 Transformando lista a array

In [93]:
arreglo = np.array(lista)
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [94]:
type(arreglo)

numpy.ndarray

Corroborando tipo de dato

In [95]:
arreglo.dtype

dtype('int32')

definiendo el array de int31 a float32

In [96]:
np.array(arreglo,dtype=np.float32)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

Sigue siendo un array de int32

In [97]:
arreglonuevo=np.arange(1,11)
arreglonuevo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [98]:
promedio = np.mean(arreglo)
promedio

5.5

In [99]:
mediana = np.median(arreglo)
mediana

5.5

In [100]:
desviacion_std = np.std(arreglo)
desviacion_std

2.8722813232690143

In [101]:
arreglo_de_ceros = np.zeros(5)
arreglo_de_ceros

array([0., 0., 0., 0., 0.])

In [147]:
arreglo_aleatorio = np.random.rand(10)
arreglo_aleatorio

array([0.33454682, 0.4248226 , 0.79110888, 0.11592893, 0.99184743,
       0.13374092, 0.25936976, 0.36080194, 0.88259745, 0.79202201])

In [149]:
matriz = np.random.rand(3,3)
matriz

array([[0.59556226, 0.24235507, 0.54268015],
       [0.12481319, 0.89391062, 0.53268008],
       [0.12507097, 0.39192776, 0.31285778]])

In [162]:
arreglo_aleatorio2 = np.random.randint(1,1001,10)
arreglo_aleatorio2

array([115, 253, 459,  26, 114, 440, 857, 695, 273, 550])

In [167]:
matriz2 = np.random.randint(1,101,(10,10))
matriz2

array([[  5,   6,  76,  55,  10,  20,  56,  95,  34,  85],
       [ 10,  90,  10,   1,  93,  39,  50,  23,  74,  21],
       [ 89,  16,  90,  23,  46,  69,  60,  49,  12,  43],
       [ 73,  49,  98,  52,  21,  48,  15,  49,  10,  32],
       [ 39,  92,  35,  25,   5,  39,  52,  20,   1,  46],
       [  2,  86,  24,  84, 100,  66,  24,  96,  64,  38],
       [ 84,   1,  85,  31,  10,  98,  67,  68,  41,  31],
       [ 11,   6,  73,  89,  83,  43,  83,  58,   1,  33],
       [ 38,  23,  86,  80,  83,  19,  42,  77,   1,  89],
       [ 26,  30,  30,  88,  84,   3,  88,  99,  68,  51]])