In [10]:
import numpy as np
import matplotlib.pyplot as plt


A. Crear un array de 10 elementos. Los elementos de este array deben ser consecutivos
del 1 al 10. Este array no debe ser aleatorio.


In [26]:
arreglo = np.arange(1,11)
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

B. Crear un segundo array de 10 elementos. Este array si debe ser aleatorio. Los valores
deben ser enteros entre el 1 al 20.

In [39]:
arreglo_aleatorio = np.random.randint(1,21,10)
arreglo_aleatorio

array([ 5,  3,  2, 10, 19,  5,  3,  1,  3,  6])

C. Obtener un vector único de 10 elementos, sumando los dos arrays anteriores.


D. Mezclar el vector obtenido en la letra C utilizando una función vista en la Unidad IV.

E. Calcular la Mediana, el Promedio y Posiciones de Valores Máximo y Mínimo utilizando
las funciones vistas en la Unidad IV. Tomar el vector de la letra D.


In [41]:
mediana = np.mean(arreglo)
mediana

5.5

In [42]:
promedio = np.median(arreglo)
promedio

5.5

In [ ]:
posicion_maxima = np.()

In [ ]:
posicion_minimo = np.()

F. Transformar el vector obtenido en una Matriz de 2 x 5

In [40]:
matriz = arreglo.reshape(2, 5)
matriz

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])