In [10]:
import matplotlib.pyplot as plt
import numpy as np

In [20]:
lista = [1,3,5]
print(lista)

[1, 3, 5]


Matriz de una dimension

In [22]:
matriz = np.array([1,2,3,4,5])
print(matriz)

[1 2 3 4 5]


matriz de dos dimensiones

In [25]:
m2d = np.array([[1,2,3], [4,5,6]])
print(m2d)

[[1 2 3]
 [4 5 6]]


Creando matriz con lista

In [26]:
lista =[1,2,3,4,5]
matriz = np.array(lista)
print(matriz)

[1 2 3 4 5]


matriz 3*3

In [28]:
lista = [[1,2,3],[4,5,6],[7,8,9]]
matriz = np.array(lista)
print(matriz)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Generando rangos

In [41]:
matriz = np.arange(1,21).reshape(4,5)
print(matriz.shape) #Cuantas filas y columnas hay.
print(matriz.ndim) #Dice la dimension de la matriz
print(matriz.size) #Cuenta la cantidad de elementos
print(matriz)

(4, 5)
2
20
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


Matriz